package claudelog

import (
	"strings"
	"testing"
)

func TestTitle_NilSession(t *testing.T) {
	if got := Title(nil); got != "claude-log" {
		t.Errorf("Title(nil) = %q, want %q", got, "claude-log")
	}
}

func TestTitle_AITitlePreferred(t *testing.T) {
	s := &Session{
		AITitle:   "  Refactor sync module  ",
		SessionID: "abcdef01-rest",
		Cwd:       "/p/x",
		Messages: []Message{
			{Role: "user", Text: "hi"},
		},
	}
	got := Title(s)
	want := "Refactor sync module"
	if got != want {
		t.Errorf("Title = %q, want trimmed AITitle %q", got, want)
	}
}

func TestTitle_FirstUserPromptFallback(t *testing.T) {
	s := &Session{
		SessionID: "abcdef01-rest",
		Cwd:       "/p/x",
		Messages: []Message{
			{Role: "assistant", Text: "should be skipped"},
			{Role: "user", Text: "  please refactor parse.go  "},
			{Role: "user", Text: "second user, also skipped"},
		},
	}
	got := Title(s)
	want := "please refactor parse.go"
	if got != want {
		t.Errorf("Title = %q, want %q (first user msg trimmed)", got, want)
	}
}

func TestTitle_FirstUserPromptTruncated(t *testing.T) {
	long := strings.Repeat("x", maxFirstPromptLen+10)
	s := &Session{
		Messages: []Message{{Role: "user", Text: long}},
	}
	got := Title(s)
	if !strings.HasSuffix(got, "…") {
		t.Errorf("Title = %q, want ellipsis suffix on long prompt", got)
	}
	if runeLen := len([]rune(got)); runeLen != maxFirstPromptLen+1 {
		t.Errorf("Title rune len = %d, want %d (cap + ellipsis)", runeLen, maxFirstPromptLen+1)
	}
}

func TestTitle_SyntheticFallback(t *testing.T) {
	s := &Session{
		SessionID: "abcdef0123-rest",
		Cwd:       "/Users/me/Projects/dotgo",
	}
	got := Title(s)
	want := "abcdef01 dotgo"
	if got != want {
		t.Errorf("Title = %q, want %q", got, want)
	}
}

func TestTitle_SyntheticFallback_RootCwd(t *testing.T) {
	s := &Session{
		SessionID: "abcdef0123-rest",
		Cwd:       "/",
	}
	got := Title(s)
	want := "abcdef01 claude-log"
	if got != want {
		t.Errorf("Title = %q, want %q", got, want)
	}
}

func TestTitle_EmptyEverything(t *testing.T) {
	s := &Session{}
	got := Title(s)
	if got != "claude-log" {
		t.Errorf("Title = %q, want %q (must never be empty)", got, "claude-log")
	}
}

// TestTitle_BlankAITitleFallsThrough guards against treating a whitespace-
// only ai-title as a real title; that would emit an empty Name to Notion
// and violate AC4.
func TestTitle_BlankAITitleFallsThrough(t *testing.T) {
	s := &Session{
		AITitle:   "   ",
		SessionID: "abcdef01-rest",
		Cwd:       "/x",
		Messages:  []Message{{Role: "user", Text: "kept"}},
	}
	got := Title(s)
	if got != "kept" {
		t.Errorf("Title = %q, want first user prompt %q", got, "kept")
	}
}

// TestTitle_FallbackUsesFirstJSONLPrompt ties together AC5: the synthetic
// path is reachable only when no user prompt exists, so when the user has
// spoken at least once that prompt is the layer 2 source of truth.
func TestTitle_FallbackUsesFirstJSONLPrompt(t *testing.T) {
	s := &Session{
		SessionID: "abcdef01-rest",
		Cwd:       "/x",
		Messages: []Message{
			{Role: "user", Text: "hello world"},
			{Role: "assistant", Text: "hi"},
		},
	}
	if got := Title(s); got != "hello world" {
		t.Errorf("Title = %q, want %q (AC5: fallback uses first JSONL prompt)", got, "hello world")
	}
}

// TestTitle_SkipsSystemInjectedCaveat (Issue #20): slash-command sessions
// inject "<local-command-caveat>..." as the first user entry; Layer 2 must
// skip it and pick the next genuine user message instead.
func TestTitle_SkipsSystemInjectedCaveat(t *testing.T) {
	s := &Session{
		SessionID: "abcdef01-rest",
		Cwd:       "/x",
		Messages: []Message{
			{Role: "user", Text: "<local-command-caveat>Caveat: The messages below were generated by the user while running the /build-feature command</local-command-caveat>"},
			{Role: "user", Text: "implement feature X please"},
		},
	}
	if got := Title(s); got != "implement feature X please" {
		t.Errorf("Title = %q, want %q (Issue #20: caveat must be skipped)", got, "implement feature X please")
	}
}

// TestTitle_SkipsSessionStartHook (Issue #20): hook output injected as user
// entry must also be skipped.
func TestTitle_SkipsSessionStartHook(t *testing.T) {
	s := &Session{
		SessionID: "abcdef01-rest",
		Cwd:       "/x",
		Messages: []Message{
			{Role: "user", Text: "<session-start-hook>OK</session-start-hook>"},
			{Role: "user", Text: "real prompt"},
		},
	}
	if got := Title(s); got != "real prompt" {
		t.Errorf("Title = %q, want %q", got, "real prompt")
	}
}

// TestTitle_SkipsCommandWrapper (Issue #20): /command invocations inject
// <command-message>, <command-name>, <command-args> as separate user entries.
func TestTitle_SkipsCommandWrapper(t *testing.T) {
	s := &Session{
		Messages: []Message{
			{Role: "user", Text: "<command-message>build-feature</command-message>"},
			{Role: "user", Text: "<command-name>/build-feature</command-name>"},
			{Role: "user", Text: "<command-args>#20</command-args>"},
			{Role: "user", Text: "actual request"},
		},
	}
	if got := Title(s); got != "actual request" {
		t.Errorf("Title = %q, want %q (all command-* tags must be skipped)", got, "actual request")
	}
}

// TestTitle_AllInjectedFallsToSynthetic (Issue #20): when every user entry
// is system-injected, Layer 2 yields nothing and Layer 3 synthetic title
// must fire instead of producing a caveat-named page.
func TestTitle_AllInjectedFallsToSynthetic(t *testing.T) {
	s := &Session{
		SessionID: "abcdef01-rest",
		Cwd:       "/Users/me/Projects/dotfiles",
		Messages: []Message{
			{Role: "user", Text: "<local-command-caveat>Caveat...</local-command-caveat>"},
			{Role: "user", Text: "<session-start-hook>OK</session-start-hook>"},
		},
	}
	got := Title(s)
	want := "abcdef01 dotfiles"
	if got != want {
		t.Errorf("Title = %q, want synthetic %q (all user msgs injected)", got, want)
	}
}

// TestTitle_PreservesLegitimateAngleBracketStart (Issue #20 risk guard):
// user-authored prompts beginning with a tag we don't recognise must NOT
// be stripped. Only Claude-Code protocol tags are filtered.
func TestTitle_PreservesLegitimateAngleBracketStart(t *testing.T) {
	s := &Session{
		Messages: []Message{
			{Role: "user", Text: "<example> tell me about <example> tags"},
		},
	}
	if got := Title(s); got != "<example> tell me about <example> tags" {
		t.Errorf("Title = %q, want untouched user content", got)
	}
}

// TestIsSystemInjectedText covers the prefix matcher in isolation so that
// future additions to the prefix list have a clear test point.
func TestIsSystemInjectedText(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"<local-command-caveat>x</local-command-caveat>", true},
		{"<local-command-stdout>...</local-command-stdout>", true},
		{"<local-command-stderr>err</local-command-stderr>", true},
		{"<session-start-hook>OK</session-start-hook>", true},
		{"<session-end-hook>OK</session-end-hook>", true},
		{"<command-message>x</command-message>", true},
		{"<command-name>/foo</command-name>", true},
		{"<command-args>--bar</command-args>", true},
		{"<user-prompt-submit-hook>OK</user-prompt-submit-hook>", true},
		{"   <local-command-caveat>x</local-command-caveat>", true}, // leading ws tolerated
		{"<example>not stripped</example>", false},
		{"hello", false},
		{"", false},
		{"<thinking>assistant tag, not user</thinking>", false}, // out-of-scope, not in list
	}
	for _, c := range cases {
		if got := isSystemInjectedText(c.in); got != c.want {
			t.Errorf("isSystemInjectedText(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}
